version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
